### ISSUE TITLE
ArgumentException: Could not find method overriding method with nested generics

### ISSUE THREAD

**Issue by BitWizJason** [castleproject/Core#297]
Visual Studio Enterprise 2017 Version 15.2 (26430.16) Release
Target framework: .NET Framework 4.6.1
Castle.Core (3.3.0)

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=Could not find method overriding System.Threading.Tasks.Task`1[System.Collections.Generic.List`1[TEntity]] GetAllCache[TEntity,TEntityPrimaryKey](Abp.Domain.Repositories.IRepository`2[TEntity,TEntityPrimaryKey], System.String, System.Linq.Expressions.Expression`1[System.Func`2[TEntity,System.Object]][]) on type DES.Employees.EmployeesAppService. This is most likely a bug. Please report it.
  Source=Castle.Core
  StackTrace:
   at Castle.DynamicProxy.Internal.InvocationHelper.ObtainMethod(MethodInfo proxiedMethod, Type type)
   at Castle.DynamicProxy.Internal.InvocationHelper.GetMethodOnType(Type type, MethodInfo proxiedMethod)
   at Castle.DynamicProxy.Internal.InheritanceInvocation.get_MethodInvocationTarget()
   at Abp.Domain.Uow.UnitOfWorkInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Abp.Auditing.AuditingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Abp.Runtime.Validation.Interception.ValidationInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.EmployeesAppServiceProxy.GetAllCache[TEntity,TEntityPrimaryKey](IRepository`2 repository, String cacheName, Expression`1[] entityIncludes)
   at DES.Shared.AbstractCrudDESAppServiceBase.<GetAll>d__4`4.MoveNext() in \DES\src\DES.Application\Shared\AbstractCrudDESAppServiceBase.cs:line 101
```

**Comment by BitWizJason** [comment]
Method Base Class:

        public virtual async Task<List<TEntity>> GetAllCache<TEntity, TEntityPrimaryKey>(IRepository<TEntity, TEntityPrimaryKey> repository, [CallerMemberName] string cacheName = "", params Expression<Func<TEntity, object>>[] entityIncludes)
            where TEntity : Entity<TEntityPrimaryKey>
        {
            return await CacheManager
                .GetCache<string, List<TEntity>>(this.GetMethodCacheName(cacheName))
                .GetAsync(AllCacheKey, async () => await repository.GetAllIncluding(entityIncludes).ToListAsync().ConfigureAwait(false))
                .ConfigureAwait(false);
        }

Method implementing class:

        public override async Task<List<TEntity>> GetAllCache<TEntity, TEntityPrimaryKey>(IRepository<TEntity, TEntityPrimaryKey> repository, [CallerMemberName] string cacheName = "",
            params Expression<Func<TEntity, object>>[] entityIncludes)
        {
            if (entityIncludes == null)
            {
                return await base.GetAllCache(repository, cacheName, 
                    entity => (entity as Employee).User);
            }

            return await base.GetAllCache(repository, cacheName, entityIncludes);
        }

**Comment by BitWizJason** [comment]
Verified issue still occurs in Castle.Core (4.1.1)

**Comment by jonorossi** [comment]
@BitWizJason could you please provide a runnable test case, it doesn't need to use NUnit just create a `ProxyGenerator`.

It would be great if you can reduce the test to what causes the problem, i.e. is it because its async, the generic parameters, the first actual parameter being a generic, the parameter with a default value, the parameter with `[CallerMemberName]`, or the `params` parameter.

**Comment by BitWizJason** [comment]
@jonorossi Will do!

**Comment by BitWizJason** [comment]
@jonorossi I created a pull request with test cases and a potential fix #303

**Comment by jonorossi** [comment]
Thanks @BitWizJason, merged.

**Comment by backjacklao** [comment]
This issue still occurs in Castle.Core (4.4.1)
