### ISSUE TITLE
TargetInvocationException and OutOfMemoryException

### ISSUE THREAD

**Issue by Narutofox** [castleproject/Core#363]
I use Castle in my ASP.NET MVC project and I use it in my factory to create a proxy to repositories.
In debug it work's fine but in production after certain amount of time I get TargetInvocationException and OutOfMemoryException.

Version: Castle.Core 4.2.1

**InnerException:** System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Castle.DynamicProxy.ProxyGenerationException: There was an error in static constructor on type Castle.Proxies.IUserDALProxy. This is likely a bug in DynamicProxy. Please report it. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Castle.Proxies.IUserDALProxy' threw an exception. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at Castle.Proxies.IUserDALProxy..cctor() --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized) at System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark) at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture) at Castle.DynamicProxy.Internal.TypeUtil.SetStaticField(Type type, String fieldName, BindingFlags additionalFlags, Object value) --- End of inner exception stack trace --- at Castle.DynamicProxy.Internal.TypeUtil.SetStaticField(Type type, String fieldName, BindingFlags additionalFlags, Object value) at Castle.DynamicProxy.Generators.BaseProxyGenerator.InitializeStaticFields(Type builtType) at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateType(String typeName, Type proxyTargetType, Type[] interfaces, INamingScope namingScope) at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.<>c__DisplayClass6_0.b__0(String n, INamingScope s) at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory) at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode(Type proxyTargetType, Type[] interfaces, ProxyGenerationOptions options) at Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, Type targetType, ProxyGenerationOptions options) at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, Object target, ProxyGenerationOptions options, IInterceptor[] interceptors) at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithTarget[TInterface](TInterface target, IInterceptor[] interceptors) at CronelAssessments.Factories.DALFactory.GetUserDAL(String localContextConnectionString, LoginUser loginUser, IHelper helper) at CronelAssessments.Controllers.CandidateController..ctor() --- End of inner exception stack trace --- at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) at System.Activator.CreateInstance(Type type, Boolean nonPublic) at System.Activator.CreateInstance(Type type) at System.Web.Mvc.DefaultControllerFactory.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType)

**StackTrace:** at System.Web.Mvc.DefaultControllerFactory.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType) at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType) at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) at Castle.Proxies.Invocations.IControllerFactory_CreateController.InvokeMethodOnTarget() at 
Castle.DynamicProxy.AbstractInvocation.Proceed() at Castle.Proxies.IControllerFactoryProxy.CreateController(RequestContext requestContext, String controllerName) at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory) at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

This is how my code in factory looks like:

```
public static class DALFactory
{
        private static readonly Castle.DynamicProxy.ProxyGenerator proxy;
        static DALFactory()
        {
            proxy = new Castle.DynamicProxy.ProxyGenerator();
        }

       public static IUserDAL GetUserDAL()
        {           
            IUserDAL dalInterface = UserDAL.GetInstance();
            return proxy.CreateInterfaceProxyWithTarget(dalInterface, new AOP.DALInterceptor());
        }
}
```

**Comment by stakx** [comment]
@Narutofox - Just passing by... I would suggest that you add a small but complete code example that reproduces the problem you're reporting. It's hard to tell what's going wrong by just looking at the code you've posted. At the very least, you'd probably have to add the definition of the type you're trying to proxy (`IUserDAL`).

**Comment by jonorossi** [comment]
You'll need to do some investigation where your memory is going. You obviously believe it is DynamicProxy eating all your memory, so I'd either turn on the logging which can tell you about cache misses, etc, or add some logging to production to write out `ProxyGenerator.ProxyBuilder.ModuleScope.StrongNamedModule.Assembly.GetTypes().Length`. You could obviously also use other debugging tools like dotTrace.

One tip is to use `CreateInterfaceProxyWithTarget<TInterface>()` properly so that it only proxies the required methods defined in the interface, not all virtual class methods.

**Comment by Narutofox** [comment]
When i log 
`ProxyGenerator.ProxyBuilder.ModuleScope.StrongNamedModule.Assembly.GetTypes().Length`
 length starts from 3 and it keeps climbing, highest so far is 527. This is in debug i have yet to try it on production

**Comment by stakx** [comment]
I would suggest to you to create a minimal but complete code example that reproduces the problem, then post it here. Usually reducing a problem situation to its core helps figuring out already what's going wrong.
