### ISSUE TITLE
NullReferenceException creating proxy

### ISSUE THREAD

**Issue by rynowak** [castleproject/Core#410]
We're seeing the following exception occur sporadically on `netcoreapp2.2`.

This line in particular seems suspect to me: https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/ModuleScope.cs#L177 - it's my understanding that a `Dictionary<,>` is not thread safe for reading when any number of writers are allowed. I'm wondering if this is a new failure based on some code changes in the dictionary implementation for `netcoreapp2.2`.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Castle.DynamicProxy.ModuleScope.GetFromCache(CacheKey key)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.GetFromCache(CacheKey key)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions options)
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
   at Moq.Mock`1.<InitializeInstance>b__20_0()
   at Moq.PexProtector.Invoke(Action action)
   at Moq.Mock`1.InitializeInstance()
   at Moq.Mock`1.OnGetObject()
   at Moq.Mock.GetObject()
   at Moq.Mock.get_Object()
   at Moq.Mock`1.get_Object()
   at Moq.Mocks.CreateMocks[T]()+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.EnumerableExecutor`1.Execute()
   at System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[TElement](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at Moq.Linq.MockQueryable`1.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
```

**Comment by stakx** [comment]
@rynowak: Just to make sure, which version of Castle.Core are you using?

**Comment by rynowak** [comment]
Using Castle.Core 4.1.0 via Moq 4.7.49

**Comment by stakx** [comment]
@rynowak: I suspected so. We've recently fixed a bug in DynamicProxy that would have caused this bug. See also https://github.com/moq/moq4/issues/653.

Please update to a recent version of Moq (and Castle Core) to resolve this problem.

**Comment by rynowak** [comment]
Thanks! we'll give it a try

**Comment by stakx** [comment]
@rynowak: Any news on this? Are you still seeing any `NullReferenceException`s after upgrading?

**Comment by rynowak** [comment]
Sorry for going dark. We upgraded and have no seen this issue reoccur, so I'm close things. Thanks for everything that you do!
