### ISSUE TITLE
Dynamic Proxy generation fails for Interfaces with init properties

### ISSUE THREAD

**Issue by tobuto** [castleproject/Core#600]
I discovered this when using `Moq` to mock an interface with a read only property, e.g.
```
interface ITest {
    object Property { get; init; }
}
```

This causes an exception in `BaseProxyGenerator.InitializeStaticFields` call to `TypeUtil.SetStaticField`. This is the stack trace for the exception:

```
Castle.DynamicProxy.ProxyGenerationException
There was an error in static constructor on type Castle.Proxies.ITestProxy. This is likely a bug in DynamicProxy. Please report it.
   at Castle.DynamicProxy.Internal.TypeUtil.SetStaticField(Type type, String fieldName, BindingFlags additionalFlags, Object value)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.InitializeStaticFields(Type builtType)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithoutTargetGenerator.GenerateType(String typeName, Type proxyTargetType, Type[] interfaces, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.<>c__DisplayClass6_0.<GenerateCode>b__0(String n, INamingScope s)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.<>c__DisplayClass33_0.<ObtainProxyType>b__0(CacheKey _)
   at Castle.Core.Internal.SynchronizedDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode(Type proxyTargetType, Type[] interfaces, ProxyGenerationOptions options)
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor[] interceptors)
   at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments) in C:\projects\moq4\src\Moq\ProxyFactories\CastleProxyFactory.cs:line 50
   at Moq.Mock`1.InitializeInstance() in C:\projects\moq4\src\Moq\Mock`1.cs:line 311
   at Moq.Mock`1.OnGetObject() in C:\projects\moq4\src\Moq\Mock`1.cs:line 325
   at Moq.Mock.get_Object() in C:\projects\moq4\src\Moq\Mock.cs:line 179
   at Moq.Mock`1.get_Object() in C:\projects\moq4\src\Moq\Mock`1.cs:line 283
```

Let me know if you need any other infos.

**Comment by jonorossi** [comment]
Unassigning from v5.0 milestone. No one was contributed or is discussing a possible fix.

**Comment by stakx** [comment]
@tobuto, I cannot reproduce your reported issue with the current version DynamicProxy. I've run the following repro code on `net48`, `netcoreapp2.1`, `netcoreapp3.1`, `net5.0`, and `net6.0`. No errors.

```csharp
using Castle.DynamicProxy;

#if !NET5_0_OR_GREATER

namespace System.Runtime.CompilerServices
{
    public class IsExternalInit { }
}

#endif

public interface IHaveInitOnlySetter
{
    object Property { get; init; }
}

class Program
{
    static void Main()
    {
        var generator = new ProxyGenerator();
        _ = generator.CreateInterfaceProxyWithoutTarget<IHaveInitOnlySetter>(new StandardInterceptor());
    }
}
```

Am I missing something?

**Comment by VagnerSilva** [comment]
I have the same problem occurs only in .Net5 version.
Here is an example


```csharp
using Castle.DynamicProxy;

#if !NET5_0_OR_GREATER

namespace System.Runtime.CompilerServices
{
    public class IsExternalInit { }
}

#endif

public  interface IProperty
{
    string Name { get; set;  }
}

public interface IHaveInitOnlySetter<T>
{
    T Property { get; init; }
}

class Program
{
    static void Main()
    {
        var generator = new ProxyGenerator();
        _ = generator.CreateInterfaceProxyWithoutTarget<IHaveInitOnlySetter<IProperty>>(new StandardInterceptor());
    }
}
```

**Comment by VagnerSilva** [comment]
> I'm closing this stale issue, the reported "bug" is not reproducible.

I have the same problem occurs only in .Net5 version.
Here is an example


```csharp
using Castle.DynamicProxy;
using System.Collections.Generic;

#if !NET5_0_OR_GREATER

namespace System.Runtime.CompilerServices
{
    public class IsExternalInit { }
}

#endif

public  interface IProperty
{
    string Name { get; set;  }
}

public interface IHaveInitOnlySetter<T>
{
    List<T> Property { get; init; }
}

class Program
{
    static void Main()
    {
        var generator = new ProxyGenerator();
        _ = generator.CreateInterfaceProxyWithoutTarget<IHaveInitOnlySetter<IProperty>>(new StandardInterceptor());
    }
}
```

**Comment by stakx** [comment]
@VagnerSilva, I believe it's the combination of `init` and property's the generic return type. Citing myself from a different issue (https://github.com/moq/moq/issues/1148#issue-832204776):

> The issue is caused by a bug inside System.Reflection.Emit (https://github.com/dotnet/runtime/issues/25958), which causes method signatures to be reproduced incorrectly if the original method signature happens to include a [modreq](https://github.com/stakx/ecma-335/blob/master/docs/ii.7.1.1-modreq-and-modopt.md#ii711-modreq-and-modopt), and if the method is either generic or in a generic type. Lately, the IL metadata encodings for new C# language features increasingly rely on such modreqs (see e.g. [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init#metadata-encoding) for `init`-only setters, or [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.2/readonly-ref#metadata-representation-of-in-parameters) for `in` parameters), that's why they're affected by this bug.

That runtime bug was fixed in .NET 6, so if you're on .NET 5 or earlier, I suggest that you upgrade.
