### ISSUE TITLE
`invocation.MethodInvocationTarget` throws `ArgumentNullException` for default interface method

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#684]
### Repro code

```csharp
var generator = new ProxyGenerator();
var foo = generator.CreateInterfaceProxyWithoutTarget<IFoo>(new InspectInvocation());
foo.Bar();

public interface IFoo
{
    void Bar() { }
}

public class InspectInvocation : IInterceptor
{
    public void Intercept(IInvocation invocation)
    {
        Debug.Assert(invocation.InvocationTarget == null || invocation.MethodInvocationTarget != null);  // will throw
    }
}
```

### Expected outcome

Unless I misunderstand the meaning of `IInvocation.InvocationTarget` and `IInvocation.MethodInvocationTarget`, I would expect the latter to point to a method of the former's type, if the former (`IInvocation.InvocationTarget`) is non-null.

### Actual outcome

`MethodInvocationTarget` will throw an `ArgumentNullException` due to the invocation's `targetType` not being set.

### Affected version(s)

Castle.Core starting at tag `v5.2.0`

/cc @dtchepak @zvirja @alexandrnikitin &ndash; this will likely matter for NSubstitute (in https://github.com/nsubstitute/NSubstitute/blob/4d258a28aba054ea18785d36b4bdd83da023aefb/src/NSubstitute/Proxies/CastleDynamicProxy/CastleInvocationMapper.cs#L11-L16) once we've published version 5.2.0 and you upgrade to that version.

**Comment by stakx** [comment]
If I understand things correctly, then generally speaking the "target" is whatever one can `.Proceed()` to:

* For composition-based proxies, a target object can be supplied explicitly.
* For inheritance-based proxies, the target can be either missing (i. e. `null`) or the intercepted method's implementation inherited from the proxied type.

If the above assumptions are correct, then for an `IInvocation` representing an intercepted default interface method...:

* `invocation.TargetType` should return the interface type where the default implementation resides.
* `invocation.InvocationTarget` should return the same as `invocation.Proxy`.
* `invocation.MethodInvocationTarget` should return the `MethodInfo` of the method with the default implementation... so possibly the same as `invocation.Method`?

@jonorossi, sorry to bother you again, but are my assumptions and deductions correct, or am I missing some finer distinctions?

**Comment by 304NotModified** [comment]
I see 5.2.1 now on nuget.org 🎉

**Comment by 304NotModified** [comment]
FYI I tested this with NSubstitute 5.3.0 and Castle.Core 5.1.1 and 5.2.1

Tested with the following code:
```csharp
    [Fact]
    public void TestDefaultInterfaceImpl1()
    {
        // Arrange
        var for1 = Substitute.For<IMyInterface>();

        // Act
        var message = for1.GetText();

        // Assert
        message.Should().Be("abc");

    }

    [Fact]
    public void TestDefaultInterfaceImpl2()
    {
        // Arrange
        var for1 = Substitute.For<IMyInterface>();
        for1.GetText().Returns("abc");

        // Act
        var message = for1.GetText();

        // Assert
        message.Should().Be("abc");

    }

    public interface IMyInterface
    {
        string GetText()
        {
            return "abc";
        }
    }
```

### Castle.Core 5.1.1:
- Test TestDefaultInterfaceImpl1 fails: Expected message to be "abc" with a length of 3, but "" has a length of 0, differs near "" (index 0).
- Test TestDefaultInterfaceImpl2 succeeds

### Castle.Core 5.2.1
Both tests fail with:

> System.ArgumentNullException
Value cannot be null. (Parameter 'type')
   at Castle.DynamicProxy.Internal.InvocationHelper.GetMethodOnType(Type type, MethodInfo proxiedMethod)
   at Castle.DynamicProxy.Internal.InheritanceInvocation.get_MethodInvocationTarget()
   at NSubstitute.Proxies.CastleDynamicProxy.CastleInvocationMapper.Map(IInvocation castleInvocation)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy.GetText()

**Comment by stakx** [comment]
@304NotModified, thanks for adding some more test cases to this issue, plus thinking about the meaning of those invocation properties. I'll see what I can do... but it might take a while (hopefully not another 6 months though...).

**Comment by BecaLParker** [comment]
I'm watching for a resolution to this issue as it's blocking us from taking the latest update - thanks :)

**Comment by stakx** [comment]
@304NotModified and @vis-cal, I've finally figured out a bugfix that I actually understand myself (which is to say that I'm fairly confident in its correctness). See the PR linked above.

For interface methods with a default implementation, `invocation.MethodInvocationTarget` should now return that (callable) method, and (at least for proxies without target) `invocation.InvocationTarget` will return the proxy itself.

I have run @304NotModified's [test cases posted above](https://github.com/castleproject/Core/issues/684#issuecomment-2710408220) against the updated DynamicProxy code, with the following result:

* Neither `TestDefaultInterfaceImpl1` nor `TestDefaultInterfaceImpl2` throw an `ArgumentNullException` anymore.
* `TestDefaultInterfaceImpl1` still fails, like it did with Castle.Core 5.1.1. (I suspect that there's something going on inside NSubstitute that causes it to decide against performing a call to `base`. The `ReturnFromBaseIfRequired` route handler skips right over the `call.TryCallBase()`. I'll obviously leave that to you.)
* `TestDefaultInterfaceImpl1` succeeds.

**Comment by 304NotModified** [comment]
@stakx I can confirm that this issue in Castle Core 5.2.1 has been fixed in 6.0.0 preview (taken from https://ci.appveyor.com/project/castleproject/core/builds/53542581/job/b0vpahb8rymgngak/artifacts)

**Comment by stakx** [comment]
@304NotModified, that is good to hear, thanks for letting us know!

Now, if only 6.0.0 could actually be released...

**Comment by zvirja** [comment]
@stakx Let's make it happen. Now I am intrigued by your follow up 😅

**Comment by stakx** [comment]
@zvirja, the roadblock isn't that one still-open issue where we're discussing, but the expired NuGet API token (which I have no control over, and I have been unable to reach the powers that be).
